Repository eternal-system/react-cli, pull requests merged in 2020-07, with the labels that each got.

#48 Feature | #47 | refactoring select folder component
  packages/cli-ui/public/icons/add.svg
  packages/cli-ui/public/icons/arrow-down-filled.svg
  packages/cli-ui/public/icons/arrow-up.svg
  packages/cli-ui/public/icons/close.svg
  packages/cli-ui/public/icons/dark-mode.svg
  packages/cli-ui/public/icons/edit-pen.svg
  packages/cli-ui/public/icons/folder-create-filled.svg
  packages/cli-ui/public/icons/folder-filled.svg
  packages/cli-ui/public/icons/folder.svg
  packages/cli-ui/public/icons/light-mode.svg
  packages/cli-ui/public/icons/more-vert-settings.svg
  packages/cli-ui/public/icons/nav-import.svg
  packages/cli-ui/public/icons/nav-projects.svg
  packages/cli-ui/public/icons/nav-select-folder.svg
  packages/cli-ui/public/icons/refresh.svg
  packages/cli-ui/public/icons/star-filled.svg
  packages/cli-ui/public/icons/star.svg
  packages/cli-ui/public/icons/translate.svg
  packages/cli-ui/public/icons/visible-filled.svg
  packages/cli-ui/public/manifest.json
  packages/cli-ui/routes/api/folders.js
  packages/cli-ui/src/App.tsx
  packages/cli-ui/src/components/Content/style.module.scss
  packages/cli-ui/src/components/Folders/Folders.tsx
  packages/cli-ui/src/components/Folders/ItemFolder.tsx
  packages/cli-ui/src/components/Folders/style.module.scss
  packages/cli-ui/src/components/Footer/Footer.tsx
  packages/cli-ui/src/components/Footer/style.module.scss
  packages/cli-ui/src/components/Header/style.module.scss
  packages/cli-ui/src/components/Layout/Layout.tsx
  packages/cli-ui/src/components/Layout/style.module.scss
  packages/cli-ui/src/components/Modal/Modal.tsx
  packages/cli-ui/src/components/Modal/style.module.scss
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
  packages/cli-ui/src/components/Toolbar/style.module.scss
  packages/cli-ui/src/containers/DashboardContainer/Dashboard.tsx
  packages/cli-ui/src/containers/ProjectContainer/ProjectContainer.tsx
  packages/cli-ui/src/containers/ProjectContainer/projectContainer.hook.ts
  packages/cli-ui/src/containers/ProjectContainer/style.module.scss
  packages/cli-ui/src/i18n/index.ts
  packages/cli-ui/src/i18n/locales/en.ts
  packages/cli-ui/src/i18n/locales/index.ts
  packages/cli-ui/src/i18n/locales/ru.ts
  packages/cli-ui/src/modals/ModalFolder.tsx
  packages/cli-ui/src/pages/Import.tsx
  packages/cli-ui/src/pages/SelectCreateFolder.tsx
  packages/cli-ui/src/pages/SelectFolder.tsx
  packages/cli-ui/src/pages/index.ts
  packages/cli-ui/src/router/appRoutes.ts
  packages/cli-ui/src/style/main.module.scss
  packages/cli-ui/src/style/main.scss
  packages/cli-ui/src/style/vars.scss
  packages/cli-ui/webpack.config.js
Labels: bug, feature

#49 chore | #47 | update structure
  packages/cli-ui/public/icons/attach-file.svg
  packages/cli-ui/public/icons/home-filled.svg
  packages/cli-ui/src/App.tsx
  packages/cli-ui/src/components/Empty/Empty.tsx
  packages/cli-ui/src/components/Empty/index.ts
  packages/cli-ui/src/components/Empty/style.module.scss
  packages/cli-ui/src/components/Folders/Folders.tsx
  packages/cli-ui/src/components/Footer/Footer.tsx
  packages/cli-ui/src/components/Footer/style.module.scss
  packages/cli-ui/src/components/Toolbar/style.module.scss
  packages/cli-ui/src/components/index.ts
  packages/cli-ui/src/containers/ProjectContainer/ProjectContainer.tsx
  packages/cli-ui/src/containers/ProjectContainer/style.module.scss
  packages/cli-ui/src/i18n/locales/en.ts
  packages/cli-ui/src/pages/Projects.tsx
  packages/cli-ui/src/pages/SelectFolder.tsx
  packages/cli-ui/src/router/router.tsx
  packages/cli-ui/src/style/main.module.scss
Labels: wontfix

#51 hotfix | #50 | fixed using to correct fonts
  packages/cli-ui/src/components/Toolbar/style.module.scss
  packages/cli-ui/src/style/fonts.scss
  packages/cli-ui/src/style/main.scss
Labels: bug

#54 Feature/add notificator functional
  packages/cli-ui/package-lock.json
  packages/cli-ui/server/routes/api/folders.js
  packages/cli-ui/src/App.tsx
  packages/cli-ui/src/api/index.ts
  packages/cli-ui/src/common/Input/Input.tsx
  packages/cli-ui/src/common/Input/index.ts
  packages/cli-ui/src/common/Input/style.module.scss
  packages/cli-ui/src/common/index.ts
  packages/cli-ui/src/components/KillPort/KillPort.tsx
  packages/cli-ui/src/context/SettingsContext.ts
  packages/cli-ui/src/hooks/settings.hook.ts
  packages/cli-ui/src/i18n/locales/en.ts
  packages/cli-ui/src/i18n/locales/ru.ts
  packages/cli-ui/src/modals/ModalFolder.tsx
  packages/cli-ui/src/pages/CreateProject.tsx
  packages/cli-ui/src/pages/CreateProject/CreateProject.tsx
  packages/cli-ui/src/pages/CreateProject/index.ts
  packages/cli-ui/src/pages/CreateProject/style.module.scss
  packages/cli-ui/src/pages/SelectFolder.tsx
Labels: feature, frontend

#56 Refactoring/add file manager component
  packages/cli-ui/src/components/FileManager/FileManager.tsx
  packages/cli-ui/src/components/FileManager/index.ts
  packages/cli-ui/src/components/Modal/Modal.tsx
  packages/cli-ui/src/components/Modal/style.module.scss
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
  packages/cli-ui/src/components/index.ts
  packages/cli-ui/src/hooks/index.ts
  packages/cli-ui/src/hooks/modal.hook.ts
  packages/cli-ui/src/i18n/locales/en.ts
  packages/cli-ui/src/i18n/locales/ru.ts
  packages/cli-ui/src/modals/FileManagerModal/FileManager.modal.tsx
  packages/cli-ui/src/modals/FileManagerModal/index.ts
  packages/cli-ui/src/modals/FileManagerModal/style.module.scss
  packages/cli-ui/src/modals/Folder.modal.tsx
  packages/cli-ui/src/modals/index.ts
  packages/cli-ui/src/pages/CreateProject/CreateProject.tsx
  packages/cli-ui/src/pages/CreateProject/style.module.scss
  packages/cli-ui/src/pages/SelectFolder.tsx
  packages/cli-ui/src/style/fonts.scss
  packages/cli-ui/src/style/main.scss
Labels: bug, feature, frontend

#58 Feature/add notification component
  packages/cli-ui/package-lock.json
  packages/cli-ui/package.json
  packages/cli-ui/src/App.tsx
  packages/cli-ui/src/common/ProgressBar/ProgressBar.tsx
  packages/cli-ui/src/common/ProgressBar/index.ts
  packages/cli-ui/src/common/ProgressBar/style.module.scss
  packages/cli-ui/src/common/index.ts
  packages/cli-ui/src/components/FileManager/FileManager.tsx
  packages/cli-ui/src/components/Toolbar/style.module.scss
  packages/cli-ui/src/hooks/index.ts
  packages/cli-ui/src/hooks/notification.hook.ts
  packages/cli-ui/src/modals/Folder.modal.tsx
  packages/cli-ui/src/style/main.scss
Labels: feature

#60 hotfix | #59 | fixed empty current path
  packages/cli-ui/src/modals/FileManagerModal/FileManager.modal.tsx
Labels: bug, frontend

#86 feature | #44 | add component to edit url path
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
  packages/cli-ui/src/components/Toolbar/style.module.scss
  packages/cli-ui/src/pages/CreateProject/CreateProject.tsx
Labels: feature, frontend

#87 feature | #44 | add clickable function to select current folder
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
Labels: feature

#92 hotfix | #91 | hotfix layout
  packages/cli-ui/src/components/DashboardWrap/style.module.scss
  packages/cli-ui/src/router/router.tsx
Labels: bug, frontend

#94 refactoring | #93 | update webpack structure
  packages/cli-ui/package-lock.json
  packages/cli-ui/package.json
  packages/cli-ui/public/icons/flash-filled.svg
  packages/cli-ui/server.dev.js
  packages/cli-ui/server.js
  packages/cli-ui/src/App.tsx
  packages/cli-ui/src/common/Input/Input.tsx
  packages/cli-ui/src/common/Select/Select.tsx
  packages/cli-ui/src/components/Empty/Empty.tsx
  packages/cli-ui/src/components/FileManager/FileManager.tsx
  packages/cli-ui/src/components/Folders/ItemFolder.tsx
  packages/cli-ui/src/components/Footer/Footer.tsx
  packages/cli-ui/src/components/Header/Header.tsx
  packages/cli-ui/src/components/KillPort/KillPort.tsx
  packages/cli-ui/src/components/KillPort/style.module.scss
  packages/cli-ui/src/components/Modal/Modal.tsx
  packages/cli-ui/src/components/ProjectManager/ProjectFilter.tsx
  packages/cli-ui/src/components/ProjectManager/ProjectList.tsx
  packages/cli-ui/src/components/ProjectManager/ProjectListItem.tsx
  packages/cli-ui/src/components/Tabs/Tabs.tsx
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
  packages/cli-ui/src/components/index.ts
  packages/cli-ui/src/containers/DashboardContainer/Dashboard.tsx
  packages/cli-ui/src/containers/ProjectContainer/ProjectContainer.tsx
  packages/cli-ui/src/index.ts
  packages/cli-ui/src/modals/FileManagerModal/FileManager.modal.tsx
  packages/cli-ui/src/modals/Folder.modal.tsx
  packages/cli-ui/src/pages/CreateProject/CreateProject.tsx
  packages/cli-ui/src/pages/Dashboard.tsx
  packages/cli-ui/src/pages/Dependencies.tsx
  packages/cli-ui/src/pages/Home.tsx
  packages/cli-ui/src/pages/Projects.tsx
  packages/cli-ui/src/pages/SelectFolder.tsx
  packages/cli-ui/src/pages/Statistics.tsx
  packages/cli-ui/src/pages/Tasks.tsx
  packages/cli-ui/src/pages/index.ts
  packages/cli-ui/src/router/appRoutes.ts
  packages/cli-ui/src/style/fonts.scss
  packages/cli-ui/tsconfig.json
  packages/cli-ui/webpack/config.dev.js
  packages/cli-ui/webpack/config.js
  packages/cli-ui/webpack/declare.d.ts
Labels: wontfix

#101 hotfix | #100 | fixed request to create project
  packages/cli-ui/public/icons/rnk-loader.svg
  packages/cli-ui/server/connectors/folders.js
  packages/cli-ui/server/connectors/projects.js
  packages/cli-ui/src/pages/CreateProject/CreateProject.tsx
Labels: bug

#108 Feature/add ws connectors
  packages/cli-ui/package-lock.json
  packages/cli-ui/package.json
  packages/cli-ui/server/connectors/dependencies.js
  packages/cli-ui/server/connectors/folders.js
  packages/cli-ui/server/connectors/index.js
  packages/cli-ui/server/connectors/logs.js
  packages/cli-ui/server/connectors/projects.js
  packages/cli-ui/server/util/modules.js
  packages/cli-ui/server/util/resolve-path.js
  packages/cli-ui/src/components/FileManager/FileManager.tsx
  packages/cli-ui/src/components/Toolbar/Toolbar.tsx
  packages/cli-ui/src/pages/Dependencies.tsx
  packages/cli-ui/src/pages/Projects.tsx
  packages/cli-ui/src/pages/SelectFolder.tsx
Labels: feature

#110 hotfix | #81 | add hot fixes
  packages/cli-ui/server/connectors/dependencies.js
  packages/cli-ui/server/connectors/folders.js
  packages/cli-ui/server/connectors/index.js
  packages/cli-ui/server/connectors/logs.js
  packages/cli-ui/server/connectors/projects.js
  packages/cli-ui/server/util/modules.js
Labels: wontfix

#112 Feature/add component list depend
  packages/cli-ui/public/icons/like.svg
  packages/cli-ui/public/icons/link.svg
  packages/cli-ui/src/components/Dependencies/ProjectDependencies.tsx
  packages/cli-ui/src/components/Dependencies/ProjectDependencyItem.tsx
  packages/cli-ui/src/components/Dependencies/index.ts
  packages/cli-ui/src/components/Dependencies/style.module.scss
  packages/cli-ui/src/components/WelcomeTips/WelcomeTips.tsx
  packages/cli-ui/src/components/WelcomeTips/style.module.scss
  packages/cli-ui/src/components/index.ts
  packages/cli-ui/src/containers/AppContainer/AppContainer.tsx
  packages/cli-ui/src/i18n/locales/en.ts
  packages/cli-ui/src/i18n/locales/ru.ts
  packages/cli-ui/src/pages/Dependencies.tsx
Labels: feature, frontend
